In [1]:
## In the first method, we will use list() to convert the set.
a=[123,'Raj','Rani',23.34]
a

[123, 'Raj', 'Rani', 23.34]

In [2]:
b=set(a)
b

{123, 23.34, 'Raj', 'Rani'}

In [3]:
c=list(b)
c

[123, 'Rani', 'Raj', 23.34]

In [4]:
type(c)

list

In [5]:
type(b)

set

In [6]:
## How to convert int to string in Python
## Using the str() function
n=24
print(type(n))

<class 'int'>


In [7]:
m=str(n)
print(type(m))

<class 'str'>


In [8]:
## How to add two strings in python with plus operator
s='Prudhvi'
t='Raj'
print(s)
print(t)

Prudhvi
Raj


In [9]:
s1="Tutorials"
s2="Point"
s3=s1+s2
s4=s1+" "+s2
print(s3)
print(s4)

TutorialsPoint
Tutorials Point


In [10]:
y= s+" "+ t
y

'Prudhvi Raj'

In [11]:
import pandas as pd

In [14]:
e=print(" ".join([s,t]))
e

Prudhvi Raj


In [15]:
## How to convert list to dictionary
f=[1,2,3,4,5,6,7,8,9,10]
g= {n:n*n for n in f}
print(g)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [16]:
a=[1,2,3,4,5,67]
g = { n:n*n for n in a}
print(g)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 67: 4489}


In [17]:
## Get the values using key
print(g[5])

25


In [18]:
## Get the values using values function
print(g.values())

dict_values([1, 4, 9, 16, 25, 4489])


In [19]:
## Get the keys using keys function
print(g.keys())

dict_keys([1, 2, 3, 4, 5, 67])


In [20]:
h=[1,2,3,4,5,6,7,8,9,10]
i=[10,20,30,40,50,60,70,80,90,100]

In [21]:
## Convert the two list into dictionary
l=dict(zip(h,i))

In [22]:
## Convert the array to dictionary
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
import numpy as np
t=[]
for i in range(1,11):
  t.append(i)
print(t)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [24]:
tuple(t)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [25]:
list(t)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
k={ n: n*n for n in a}
print(k)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [27]:
## Find the mean of a list using mean method in statistics.
from statistics import mean
def m(h):
  return mean(h)

from statistics import median
def n(h):
  return median(h)

from statistics import mode
def o(h):
  return mode(h)

In [28]:
import statistics
def j(l):
  return mean(l)

In [29]:
l=[1,2,3,4,5,6,7,8,9,10]

In [30]:
mean(l)

5.5

In [31]:
print("Mean",m(h))
print("Median",n(h))
print("Mode",o(h))

Mean 5.5
Median 5.5
Mode 1


In [32]:
## Find the mean using function
def r(h):
  return sum(h)/len(h)

In [33]:
r(h)

5.5

In [34]:
## Using for loop finding mean of the list
def cal_average(num):
    n = 0
    for i in num:
        n = n + i           
        n+i/n
    
    return n

In [35]:
def m(n):
  r=0
  for i in n:
    r=r+i
    r+i/r
  return r

In [36]:
def mean(n):
  result=0
  for i in n:
    result=result+i
    result+i/result
  return result 

In [37]:
n=[1,2,3,4,5,6,7,8,9,10]

In [38]:
mean(n)

55

In [39]:
import numpy as np
p = np.array([1,2,3,4,5,6,7,8,9,10])
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
r(p)

5.5

In [41]:
cal_average(p)

55

In [42]:
## Finding the mean medain and mode with function
def mean(t):
  return sum(t)/len(t)

def median(t):
  t.sort()
  if len(t) % 2 == 1:
    return t[len(t)//2]
  else:
    return (t[len(t)//2-1] + t[len(t)//2])/2

In [43]:
def medain(r):
  n.sort()
  if len(n) % 2 == 1:
    return n[len(n)//2]
  else:
    return (n[len(n)//2-1] + n[len(t)//2])/2

In [44]:
r=[1,2,3,4,5,6,7,7,8,2,4,6,7,9,9,3,4,5,6,7]
r

[1, 2, 3, 4, 5, 6, 7, 7, 8, 2, 4, 6, 7, 9, 9, 3, 4, 5, 6, 7]

In [45]:
median(r)

5.5

In [46]:
mean(t)

5.5

In [47]:
median(t)

5.5

In [48]:
import numpy as np
print(np.mean(t))
print(np.median(t))

5.5
5.5


In [49]:
print(np.sort(t))

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
b=np.unique(t)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a=[1,2,3,4,5,6,7,8,9,10]
b=[11,12,13,14,15,16,17,18,19,20]

In [53]:
## Convert a dictionary to list
pd.DataFrame([l])

0  1  2  3  4  5  6  7  8   9
0  1  2  3  4  5  6  7  8  9  10

In [54]:
m=["Prudhvi"]
n=["raj"]

In [55]:
pd.DataFrame({"P1": m , "P2": n})

P1   P2
0  Prudhvi  raj

In [56]:
import pandas as pd
df=pd.DataFrame(r)
df

0
0   1
1   2
2   2
3   3
4   3
5   4
6   4
7   4
8   5
9   5
10  6
11  6
12  6
13  7
14  7
15  7
16  7
17  8
18  9
19  9

In [57]:
print(mean(t))
print

5.5


<function print>

In [58]:
print(df.mean())
print(df.median())
print(df.mode())

0    5.25
dtype: float64
0    5.5
dtype: float64
   0
0  7


In [60]:
a, b, c = 0, 1, 100
while a < c:
    print(b)
    a, b = b, a+b

1
1
2
3
5
8
13
21
34
55
89
144


In [61]:
n=10
a=0
b=1
sum=0
count=1
while(count<=n):
  count+=1
  print(a)
  sum=a+b
  a=b
  b=sum

0
1
1
2
3
5
8
13
21
34


In [62]:
#initialize the list with starting elements: 0, 1
f = [0,1]
for i in range(2, 10):
    #next elment in series = sum of its previous two numbers
        ne = f[i-1] + f[i-2]
  	#append the element to the series
        f.append(ne)

print(f)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [63]:
## Fibonacci Series
f=[0,1]
for i in range(2,21):
  n = f[i-1] + f[i-2]
  f.append(n)
print(f)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]


In [64]:
a, b, maxA = 0, 1, 100
while a < maxA:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,

In [65]:
# Python program to calculate the length of the string
n="Prudhvi Raj Dowluri"
# print(len(n))
def String_length(n):
  c=0
  for i in n:
    c=c+1
  return c
print(String_length(n))

19


In [66]:
def l():
  c=0
  for i in range(1,11):
    c=c+i
  return c
l()

55

In [67]:
# Python function that accepts a string and calculate the numbers in upper and lower case latters
n="Prudhvi Raj Dowluri"


In [68]:
# Access both key and values using items() from dictionary
a={'Name':'Prudhvi','Batch':'123R'}
for i,j in a.items():
  print(i,j)

Name Prudhvi
Batch 123R


In [69]:
def average(numList):
    total = 0
    count = 0
    for num in numList:
        total += num
        count += 1

    return total / count

In [70]:
def m():
  t=0
  c=0
  for i in range(1,11):
    t += i
    c += 1
  return t/c
m()

5.5

In [71]:
def y():
  t=2.0
  c=0
  for i in range(1,21):
    t += i
    c += 1
  return t/c
y()

10.6

In [72]:
numList=[1,2,3,4,5,6,7,8,9,10]
print(average(numList))

5.5


In [73]:
n=[1,2,3,4,5,6,7,8,9,10]

In [74]:
def s(n):
  c=0
  for i in n:
    c+=i
  return c
s(n)

55

In [75]:
# Check the first and last number of a list is the same
n=[10,20,30,40,50,60]
def first_last(n):
  f=n[0]
  s=n[-1]
  print(f,s)
first_last(n)

10 60


In [76]:
def median(numList):
    total = 0
    count = 0
    for num in numList:
        total += num
        count += 1

    return total / count

In [77]:
a=[1,2,'a+3','3+2t']
a

[1, 2, 'a+3', '3+2t']

In [78]:
a='2.0K'
type(a)

str

In [79]:
import time;
ltime=time.localtime();
print(time.strftime("%a %b %d %H:%M:%S %Z %Y",ltime));

Mon Feb 27 18:23:37 UTC 2023


In [80]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

In [81]:
a.append(b)
print(a)

[1, 2, 3, 4, 5, [6, 7, 8, 9, 10]]


In [82]:
a.extend(b)
print(a)

[1, 2, 3, 4, 5, [6, 7, 8, 9, 10], 6, 7, 8, 9, 10]


In [83]:

del a[2]
print(a)

[1, 2, 4, 5, [6, 7, 8, 9, 10], 6, 7, 8, 9, 10]


In [84]:
del a[1:5]
print(a)

[1, 6, 7, 8, 9, 10]


In [85]:
a.pop(5)

10

In [86]:
a

[1, 6, 7, 8, 9]

In [87]:
b=1,2,3,'RAJ'
b

(1, 2, 3, 'RAJ')

In [90]:

f=[1,2,3,'RAJ']
f

[1, 2, 3, 'RAJ']

In [91]:
f[1]=5
f

[1, 5, 3, 'RAJ']

In [92]:
a={'Name':'Raju','Roll No':5142}
a

{'Name': 'Raju', 'Roll No': 5142}

In [93]:
print(a['Roll No'])

5142


In [94]:
print(a.keys())

dict_keys(['Name', 'Roll No'])


In [95]:
print(a.values())

dict_values(['Raju', 5142])


In [96]:
k=[1,2,3,4,"raju",5,6,7]
k.reverse()

In [97]:
k

[7, 6, 5, 'raju', 4, 3, 2, 1]

In [98]:
k[:4]

[7, 6, 5, 'raju']

In [102]:
a=int(input("Enter the numbers: "))
b=int(input("Enter the numbers: "))
c=int(input("Enter the numbers: "))
d=int(input("Enter the numbers: "))

if a>=b and a>=c and a>=d:
  print("A is big:")
elif b>=a and b>=c and b>=d:
  print(" B is big")
elif c>=a and c>=b and c>=d:
  print('C is big')
else:
  print("D is big")

Enter the numbers: 23
Enter the numbers: 45
Enter the numbers: 78
Enter the numbers: 98
D is big


In [104]:
f=float(input("Enter the temprature: "))
c=(f-32)*(5/9)
c

Enter the temprature: 34.5


1.3888888888888888

In [105]:
n=int(input("Enter Number: "))
for i in range(n):
  for j in range(i):
    print("R",end="")
  print("")

Enter Number: 10

R
RR
RRR
RRRR
RRRRR
RRRRRR
RRRRRRR
RRRRRRRR
RRRRRRRRR


In [106]:
n=int(input("Enter the Number: "))
def prime(n):
  return (n % i) == 0

Enter the Number: 10


In [107]:
# Program to check if a number is prime or not
# Input from the user
num = int(input("Enter a number: "))

# If number is greater than 1
if num > 1:
   # Check if factor exist  
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           break
   else:
       print(num,"is a prime number")
       
# Else if the input number is less than or equal to 1
else:
   print(num,"is not a prime number")

Enter a number: 45
45 is not a prime number


In [109]:
## 1 to 100 prime numbers!
n=int(input("Enter Number: "))
for i in range(1, n):
    for j in range(2, i):
      if (i % j) == 0:
        break
    else:
      print(i, end=" ")

Enter Number: 34
1 2 3 5 7 11 13 17 19 23 29 31 

In [110]:
n=int(input("Enter Number: "))
for i in range(1,n):
  if (i % n) == 0:
    print("This is not Prime")
else:
  print("This is prime")

Enter Number: 67
This is prime


In [111]:
e=[1,2,3,4,5,6,7,8,9,10,2,7,7,7,7,7]
e

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 7, 7, 7, 7, 7]

In [112]:
import statistics
print(statistics.mean(e))
print(statistics.median(e))
print(statistics.mode(e))

5.75
7.0
7


In [113]:
import numpy as np
import statistics
g=np.array([1,2,3,4,5,6,7,8,9,10])

In [114]:
print(np.mean(e))
print(np.median(e))
print(np.var(e))
print(statistics.mode(e))
print(np.std(e))

5.75
7.0
6.5625
7
2.5617376914898995


In [115]:
j=np.random.rand(2,8,4)
j

array([[[0.95379005, 0.95342519, 0.25570088, 0.09662873],
        [0.71081   , 0.99946795, 0.09244383, 0.95140756],
        [0.66493733, 0.66366628, 0.34592516, 0.37720583],
        [0.60641934, 0.87652838, 0.5215567 , 0.9685692 ],
        [0.2729019 , 0.32574837, 0.15605173, 0.52077815],
        [0.90614971, 0.51894304, 0.59557873, 0.19284033],
        [0.36858429, 0.25020123, 0.7940314 , 0.0528041 ],
        [0.97185457, 0.97093393, 0.93971382, 0.22780471]],

       [[0.29789753, 0.45338258, 0.55161294, 0.67412221],
        [0.11788673, 0.62890362, 0.74825497, 0.88550034],
        [0.28062779, 0.5602853 , 0.25291076, 0.02958304],
        [0.9766329 , 0.96760874, 0.80380999, 0.76444844],
        [0.46159141, 0.20005394, 0.05772841, 0.60997277],
        [0.87691909, 0.64419635, 0.15006578, 0.01269318],
        [0.55284757, 0.77096561, 0.15217976, 0.39124341],
        [0.95415164, 0.95570903, 0.68799069, 0.07910212]]])

In [116]:
print(np.mean(e))
print(np.median(e))
print(np.var(e))
print(statistics.mode(e))
print(np.std(e))

5.75
7.0
6.5625
7
2.5617376914898995


In [122]:
np.random.chisquare(2,4)

array([1.05656701, 4.44243925, 0.48197433, 3.3994215 ])

In [123]:
import pandas as pd
test_list = ['a','b','c','d']
df_test = pd.DataFrame(test_list,columns=['My_letters'])
df_test

My_letters
0          a
1          b
2          c
3          d

In [124]:
import numpy as np
for i in range(1,51):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 

In [125]:
np.mean(i)

50.0

In [126]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [127]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [128]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [129]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [130]:
np.random.rand(5,2)

array([[0.78760343, 0.86723627],
       [0.65492214, 0.09301534],
       [0.40326797, 0.41229068],
       [0.24810292, 0.1952711 ],
       [0.92893473, 0.43667302]])

In [131]:
n=[]
for i in range(1,11):
  n.append(i)
n

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [132]:
from scipy import stats
print(stats.mode(i))

ModeResult(mode=array([10]), count=array([1]))


In [133]:
a=[1,2,3,4,5,6,7,8,9]
b=[1,2,3,4,4,5,66]

In [134]:
a.append(b)
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, [1, 2, 3, 4, 4, 5, 66]]

In [135]:
a.extend(b)
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, [1, 2, 3, 4, 4, 5, 66], 1, 2, 3, 4, 4, 5, 66]

In [136]:
a+b

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [1, 2, 3, 4, 4, 5, 66],
 1,
 2,
 3,
 4,
 4,
 5,
 66,
 1,
 2,
 3,
 4,
 4,
 5,
 66]

In [140]:
for i in range(1,101):
  if i == 3:
    print(i,end=" ")
  else: 
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [141]:
print(*range(1,51))

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50


In [142]:
a=print(*range(1,3))

1 2


In [143]:
b=print(*range(4,101))

4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100


In [144]:
for i in range(1,11):
    if i!=3:
      print(i,end=" ")

1 2 4 5 6 7 8 9 10 

In [145]:
l=print(*range(1,11))

1 2 3 4 5 6 7 8 9 10


In [146]:
l=[1,2 ,3, 4, 5 ,6 ,7 ,8 ,9 ,10]

In [147]:
l[10::]

[]

In [150]:
n=int(input('enter'))
res=1
for i in range(1,n+1):
  
  res=res*i
print(res)
  
  

enter10
3628800


In [151]:
a=[1,2,3,4,5,6]
b=[x**2 for x in a]
b

[1, 4, 9, 16, 25, 36]

In [156]:
type(a)

tuple

In [157]:
n=input("Enter the string: ")
m=n[::-1]
print(m)

Enter the string: Raju
ujaR


In [158]:
def r():
  for i in range(1,11):
    return i

In [159]:
r()

1